apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr-deployment
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as appropriate
          # (e.g., f5networks/k8s-bigip-ctlr:1.1.0-beta.1)
          image: "f5networks/k8s-bigip-ctlr:1.1.0-beta.1"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: password
            - name: BIGIP_URL
              valueFrom:
                secretKeyRef:
                  name: bigip-credentials
                  key: url
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url=$(BIGIP_URL)",
            "--bigip-partition=GKE-test",
            "--namespace=prod",
            "--python-basedir=/app/python",
            "--log-level=DEBUG",
            "--verify-interval=30",
            "--use-node-internal=false",
            "--pool-member-type=nodeport",
            "--running-in-cluster=true"
          ]
      imagePullSecrets:
        - name: f5-docker-images
