kind: ConfigMap
apiVersion: v1
metadata:
  name: example.vs
  namespace: prod
  labels: 
    # the type of resource you want to create on the BIG-IP
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.3.json"
  data: |
    {
      "virtualServer": {
        "backend": {
          "servicePort": 80,
          "serviceName": "frontend"
        },
        "frontend": {
          "virtualAddress": {
            "port": 80,
            "bindAddr": "10.0.1.124"
          },
          "partition": "GKE-test",
          "balance": "round-robin",
          "mode": "tcp"
        }
      }
    }


